--para saber el id actual de una llave primaria

SELECT (`AUTO_INCREMENT` - 1)  AS VALOR_ACTUAL
FROM  INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'DB_INVENTARY_XAMPP'
AND   TABLE_NAME   = 'TBL_PERSONAS';

--LUEGO REALIZAR EL INSERT 
INSERT INTO `tbl_empleados`(`ID_EMPLEADO`, `USUARIO`, `PASSWORD`, `CORREO`, `CARGO`) 
VALUES ((SELECT (`AUTO_INCREMENT` - 1)  AS VALOR_ACTUAL
FROM  INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'DB_INVENTARY_XAMPP'
AND   TABLE_NAME   = 'TBL_PERSONAS'),'Usuario2','asd456','test2@gmail.com','Frontend Developer')