-- MySQL Script generated by MySQL Workbench
-- Wed Feb 17 14:51:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema articles-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema articles-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `articles-db` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `articles-db` ;

-- -----------------------------------------------------
-- Table `articles-db`.`Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `articles-db`.`Types` (
  `articleTypeId` INT NOT NULL AUTO_INCREMENT,
  `articleType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`articleTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles-db`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `articles-db`.`Articles` (
  `articleId` INT NOT NULL AUTO_INCREMENT,
  `articleTypeId` INT NOT NULL,
  `article` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `price` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`articleId`),
  INDEX `fk_Articles_Types_idx` (`articleTypeId` ASC),
  CONSTRAINT `fk_Articles_Types`
    FOREIGN KEY (`articleTypeId`)
    REFERENCES `articles-db`.`Types` (`articleTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;